USE [CMPT395]
GO

/****** Object:  Table [dbo].[Bill]    Script Date: 2018/10/16 12:20:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bill](
	[BID] [int] IDENTITY(1,1) NOT NULL,
	[CID] [int] NOT NULL,
	[EID] [int] NOT NULL,
	[Total_month] [int] NULL,
	[Hours] [int] NULL,
	[Amount] [int] NULL,
 CONSTRAINT [PK_Bill] PRIMARY KEY CLUSTERED 
(
	[BID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



INSERT INTO Bill
VALUES( 1, 111, 10,600,30);
INSERT INTO Bill
VALUES( 2, 222, 10,600,30);
INSERT INTO Bill
VALUES( 3, 333, 10,600,30);
INSERT INTO Bill
VALUES( 4, 444, 10,600,30);